# Generated by Django 2.2.2 on 2019-06-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Receivers phone number', max_length=15, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='Senders Phone number', max_length=15, verbose_name='Sender')),
                ('operator', models.CharField(help_text='The operator to send the sms from', max_length=15, verbose_name='From')),
                ('message', models.CharField(help_text='Message Text', max_length=500, verbose_name='Message Text')),
                ('block_code', models.IntegerField(blank=True, help_text='Block Code', null=True, verbose_name='Block Code')),
                ('last_try', models.DateTimeField(auto_now=True)),
                ('to', models.ManyToManyField(help_text='Recipients of the message', related_name='inbox', to='sms.Receiver', verbose_name='Recipients of the message')),
            ],
        ),
    ]
