# Generated by Django 2.2.2 on 2019-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20190622_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='retry_gap_time',
            field=models.IntegerField(default=0, help_text='Time in minutes before you can try to send a message again', verbose_name='Retry Gap Time'),
            preserve_default=False,
        ),
    ]
