# Generated by Django 2.2.2 on 2019-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_operator_retry_gap_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='api_endpoint',
            field=models.CharField(default='', help_text='API Endpoint', max_length=500, verbose_name='API Endpoint'),
            preserve_default=False,
        ),
    ]
