# Generated by Django 2.2.2 on 2019-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20190622_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'پیغام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator', 'verbose_name_plural': 'Operators'},
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(help_text='متن پیام', max_length=500, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(help_text='گیرنده پیام', max_length=15, verbose_name='گیرنده پیام'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='api_endpoint',
            field=models.CharField(help_text='api', max_length=500, verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(help_text='یک نام دلخواه برای این اپراتور', max_length=255, verbose_name='نام اپراتور'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='password',
            field=models.CharField(help_text='کلمه عبور پنل اس ام اس', max_length=255, verbose_name='کلمه عبور'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='retry_gap_time',
            field=models.IntegerField(help_text='دقایقی که تا قبل از آن نمیتوان اس ام اس را دوباره ارسال کرد', verbose_name='زمان تکرار ارسال اس ام اس'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='sender',
            field=models.CharField(help_text='شماره ارسال کننده اپراتور', max_length=15, verbose_name='شماره ارسال کننده'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='username',
            field=models.CharField(help_text='نام کاربری از پنل اس ام اس', max_length=255, verbose_name='Username'),
        ),
    ]
