# Generated by Django 2.2.1 on 2019-06-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title for Questionnaire', max_length=255, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='text of the yes no question', max_length=255, verbose_name='text')),
                ('is_ticked', models.BooleanField(default=False, help_text='is ticked for yes or no questions', verbose_name='is ticked')),
                ('question', models.ForeignKey(help_text='questionnaire of yes no question', on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_question', to='questionnaire.Questionnaire', verbose_name='questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='text for multiple choice question', max_length=255, verbose_name='text')),
                ('is_single_choice', models.BooleanField(help_text='is single choice for multiple choice questions', verbose_name='is single choice')),
                ('question', models.ForeignKey(help_text='questionnaire of multiple choice question', on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_question', to='questionnaire.Questionnaire', verbose_name='questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='text for answer of multiple choice questions', max_length=100, verbose_name='text')),
                ('is_selected', models.BooleanField(help_text='is an answer selected or not', verbose_name='is selected')),
                ('multiple_choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.MultipleChoiceQuestion', verbose_name='answer for multiple choice questions')),
            ],
        ),
    ]
