# Generated by Django 2.2.1 on 2019-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190603_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesnoquestion',
            name='is_ticked',
            field=models.BooleanField(default=False, help_text='is ticked for yes or no questions', verbose_name='is tiQSFVcked'),
        ),
    ]
