# Generated by Django 2.2.1 on 2019-06-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_descriptivequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptivequestion',
            options={'verbose_name': 'Descriptive Question', 'verbose_name_plural': 'Descriptive Questions'},
        ),
    ]
