# Generated by Django 2.2.1 on 2019-06-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'طبقه بندی', 'verbose_name_plural': 'طبقه بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='text',
            field=models.CharField(help_text='عنوان', max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='classification',
            field=models.ForeignKey(help_text='طبقه بندی تگ', on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='tag.Classification', verbose_name='طبقه بندی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(help_text='عنوان', max_length=255, verbose_name='عنوان'),
        ),
    ]
