# Generated by Django 2.2.1 on 2019-06-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of book', max_length=255, verbose_name='title')),
                ('edition', models.PositiveIntegerField(blank=True, help_text='edition of book', null=True, verbose_name='edition')),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='page count of book', null=True, verbose_name='page count')),
                ('volume', models.PositiveIntegerField(blank=True, help_text='volume of book', null=True, verbose_name='volume')),
                ('publication_year', models.PositiveIntegerField(blank=True, help_text='publication year of book', null=True, verbose_name='publication_year')),
                ('original_price', models.PositiveIntegerField(help_text='original price of book', verbose_name='original price')),
                ('price', models.PositiveIntegerField(help_text='price of book', verbose_name=' price')),
                ('type', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], default='sell', max_length=5)),
                ('authors', models.ManyToManyField(help_text='author(s) of book', related_name='authored_book', to='tag.Tag', verbose_name='author')),
                ('publisher', models.ForeignKey(help_text='publisher of book', on_delete=django.db.models.deletion.CASCADE, related_name='published_book', to='tag.Tag', verbose_name='publisher')),
                ('translators', models.ManyToManyField(help_text='translator(s) of book', null=True, related_name='translated_book', to='tag.Tag', verbose_name='translator')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
