# Generated by Django 2.2.1 on 2019-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, help_text='translator(s) of book', related_name='translated_book', to='tag.Tag', verbose_name='translator'),
        ),
    ]
