# Generated by Django 2.2.1 on 2019-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCore', '0002_auto_20190604_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('sell', 'saaaaall'), ('buy', 'buy')], default='sell', max_length=5),
        ),
    ]
