# Generated by Django 2.2.1 on 2019-06-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20190604_1615'),
        ('tag', '0001_initial'),
        ('users', '0002_auto_20190603_1630'),
        ('bookCore', '0003_auto_20190604_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='category of book', related_name='category_books', to='tag.Tag', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='is the book verified or not', verbose_name='is verified'),
        ),
        migrations.AddField(
            model_name='book',
            name='quality',
            field=models.ForeignKey(default=1, help_text='quality of book', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire', verbose_name='quality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, help_text='user of book', on_delete=django.db.models.deletion.CASCADE, related_name='users_books', to='users.UserProfile', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='author(s) of book', related_name='authored_books', to='tag.Tag', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='publisher of book', on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='tag.Tag', verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, help_text='translator(s) of book', related_name='translated_books', to='tag.Tag', verbose_name='translator'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], default='sell', max_length=5),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='image of book', upload_to='', verbose_name='image')),
                ('book', models.ForeignKey(help_text='book images', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bookCore.Book', verbose_name='book')),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False, help_text='is user selected', verbose_name='is selected')),
                ('book', models.ForeignKey(help_text='book requests', on_delete=django.db.models.deletion.CASCADE, related_name='request', to='bookCore.Book', verbose_name='book')),
                ('user', models.ForeignKey(help_text='user requested', on_delete=django.db.models.deletion.CASCADE, related_name='user_requested', to='users.UserProfile', verbose_name='user')),
            ],
        ),
    ]
