# Generated by Django 2.2.1 on 2019-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCore', '0004_auto_20190604_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='author(s) of book', limit_choices_to={'classification__text_in': ['heyvan']}, related_name='authored_books', to='tag.Tag', verbose_name='author'),
        ),
    ]
