# Generated by Django 2.2.1 on 2019-06-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookCore', '0005_auto_20190604_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='نویسنده (های) کتاب', limit_choices_to={'classification__text__in': ['author']}, related_name='authored_books', to='tag.Tag', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='دسته بندی کتاب', related_name='category_books', to='tag.Tag', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(blank=True, help_text='ویرایش کتاب', null=True, verbose_name='ویرایش'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='نشان دهنده تایید شدن یا نشدن کتاب', verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_price',
            field=models.PositiveIntegerField(help_text='قیمت پشت جلد کتاب', verbose_name='قیمت پشت جلد'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='تعداد صفحات کتاب', null=True, verbose_name='تعداد صفحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(help_text='قیمت کتاب', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, help_text='سال چاپ کتاب', null=True, verbose_name='سال چاپ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='ناشر کتاب', limit_choices_to={'classification__text__in': ['publisher']}, on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='tag.Tag', verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quality',
            field=models.ForeignKey(help_text='کیفیت کتاب', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire', verbose_name='کیفیت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='عنوان کتاب', max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, help_text='مترجم (های) کتاب', limit_choices_to={'classification__text__in': ['translator']}, related_name='translated_books', to='tag.Tag', verbose_name='مرترجم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('sell', 'فروش'), ('buy', 'خرید')], default='sell', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, related_name='users_books', to='users.UserProfile', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.PositiveIntegerField(blank=True, help_text='جلد کتاب', null=True, verbose_name='جلد'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(help_text='درخواست های کتاب', on_delete=django.db.models.deletion.CASCADE, related_name='request', to='bookCore.Book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='آیا کاربر انتخاب شده', verbose_name='انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='user',
            field=models.ForeignKey(help_text='درخواست های کاربر', on_delete=django.db.models.deletion.CASCADE, related_name='user_requested', to='users.UserProfile', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='book',
            field=models.ForeignKey(help_text='تصویر های کتاب', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bookCore.Book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='تصویر کتاب', upload_to='', verbose_name='تصویر'),
        ),
    ]
